const drinks = [
  {id:'fog',name:'山雾',emoji:'🫧',tags:'柑橘 · 茶 · 气泡',abv:'4.2%',price:28,desc:'像清晨大瑶山的一口薄雾'},
  {id:'forest',name:'瑶林',emoji:'🌿',tags:'蜂蜜 · 茶 · 草本',abv:'6.0%',price:32,desc:'草木回甘，温柔而有层次'},
  {id:'night',name:'夜瑶',emoji:'🌙',tags:'梅果 · 乌龙 · 浓郁',abv:'8.0%',price:35,desc:'适合把夜晚喝得慢一点'}
];
const state={tab:'home',history:[],cart:0,quizStep:0,quiz:{scene:'',flavor:'',strength:''},ingredients:new Set(['瑶皇酒']),pattern:0};
const app=document.querySelector('#app'), tabbar=document.querySelector('#tabbar');
const tabs=[['home','⌂','发现'],['order','◫','喝一杯'],['mix','✦','AI野调'],['mine','○','我的瑶山']];

function renderTabs(){tabbar.innerHTML=tabs.map(([id,icon,label])=>`<button class="tab ${id===state.tab?'active':''} ${id==='mix'?'ai':''}" data-tab="${id}"><span class="tab-icon">${icon}</span>${label}</button>`).join('')}
function navigate(view,push=true){if(push)state.history.push(state.tab);state.tab=view;render();app.scrollTop=0}
function render(){renderTabs(); const views={home:home,order:order,mix:mix,mine:mine,quiz:quiz,ingredients:ingredients,recipes:recipes,pattern:pattern,checkout:checkout};app.innerHTML=(views[state.tab]||home)();bind()}
function page(content){return `<div class="page">${content}</div>`}
function section(title,more=''){return `<div class="section-head"><h2>${title}</h2>${more?`<button>${more}</button>`:''}</div>`}
function drinkCards(){return `<div class="drink-scroll">${drinks.map(d=>`<article class="drink-card"><div class="drink-art ${d.id}"><div class="glass"></div></div><div class="drink-meta"><div><h3>${d.name} <small>${d.abv}</small></h3><p>${d.tags}</p></div><span class="price">¥${d.price}</span></div><div class="chips"><span class="chip">${d.desc}</span></div><button class="btn dark full add-drink" data-drink="${d.id}">立即点单</button></article>`).join('')}</div>`}
function home(){return page(`<div class="hero"><div class="hero-pattern"></div><span class="eyebrow" style="color:var(--lime)">JINXIU · GUANGXI</span><h1>今天，想怎么喝？</h1><p>让大瑶山的草木、茶香与微醺，成为你的旅行味觉记忆。</p><div class="hero-actions"><button class="btn go-quiz">AI 帮我选</button><button class="btn secondary go-mix">自己野调</button></div></div>${section('开启一杯瑶山')}<div class="quick-grid"><button class="quick-card go-order"><span class="quick-icon">🥂</span><strong>直接点一杯</strong><small>附近门店 · 即点即取</small></button><button class="quick-card go-pattern"><span class="quick-icon">◇</span><strong>瑶纹 DIY</strong><small>把这一杯变成你的</small></button></div>${section('瑶山三杯','全部酒单')}${drinkCards()}${section('寻饮地图','查看地图')}<div class="store active"><span class="store-icon">⌖</span><div><strong>金秀瑶都·山酿体验店</strong><small>距你 320m · 营业至 22:30</small></div></div>`)}
function order(){return page(`<span class="eyebrow">ORDER A DRINK</span><h1 class="title">喝一杯</h1><p class="subtitle">选择附近门店，线上下单，到店就能取。</p><div class="store active"><span class="store-icon">⌖</span><div><strong>金秀瑶都·山酿体验店</strong><small>320m · 制作约 8 分钟</small></div></div>${section('今日酒单')}<div class="list">${drinks.map(d=>`<article class="menu-item"><div class="thumb">${d.emoji}</div><div><h3>${d.name} · ${d.abv}</h3><p>${d.tags}<br>${d.desc}</p><strong>¥${d.price}</strong></div><button class="add add-drink" data-drink="${d.id}">+</button></article>`).join('')}</div>${state.cart?`<button class="cart-fab go-checkout"><span>酒篮 · ${state.cart} 杯</span><strong>去结算 →</strong></button>`:''}`)}
function mix(){return page(`<span class="eyebrow">YAO WILD MIX</span><h1 class="title">调一杯<br>自己的瑶山</h1><p class="subtitle">没有酒桌规矩。告诉 AI 你的心情，或者看看手边有什么。</p><button class="mode-card go-quiz"><span class="mode-icon">✦</span><span><strong>AI 帮我调</strong><small>30 秒匹配今天的口味</small></span><b>›</b></button><button class="mode-card go-ingredients"><span class="mode-icon">⌁</span><span><strong>看我有什么</strong><small>选择现有材料，生成可做配方</small></span><b>›</b></button><button class="mode-card"><span class="mode-icon">◉</span><span><strong>自由野调</strong><small>甜、酸、茶、酒感自由调节</small></span><b>›</b></button>${section('本周灵感')}<article class="recipe"><span class="recipe-num">01</span><span class="eyebrow">TRENDING RECIPE</span><h3>雾里青柑</h3><p>瑶皇酒 × 青柑气泡 × 乌龙茶<br>清爽度 ★★★★★　酒感 ★★☆☆☆</p><button class="btn dark save">收藏配方</button></article>`)}
function quiz(){const steps=[{q:'今天为什么喝？',key:'scene',opts:[['旅行尝鲜','🧳'],['一个人放松','🎧'],['朋友小聚','🥂'],['晚餐搭配','🍽️'],['夜晚微醺','🌙']]},{q:'想喝什么感觉？',key:'flavor',opts:[['清爽','🫧'],['酸甜','🍊'],['茶感','🍵'],['草本','🌿'],['浓郁','🌰']]},{q:'想喝多重？',key:'strength',opts:[['轻轻一杯','🪶'],['微醺刚好','☁️'],['有点感觉','🔥'],['酒感明显','⚡']]}];if(state.quizStep>=3)return result();const s=steps[state.quizStep];return page(`<span class="eyebrow">AI TASTE MATCH · 0${state.quizStep+1}/03</span><h1 class="title">${s.q}</h1><p class="subtitle">跟着直觉选，没有标准答案。</p><div class="quiz-progress"><i style="width:${(state.quizStep+1)/3*100}%"></i></div><div class="choices">${s.opts.map(([o,e])=>`<button class="choice ${state.quiz[s.key]===o?'active':''}" data-choice="${o}" data-key="${s.key}"><span>${e}</span>${o}</button>`).join('')}</div><div class="bottom-action"><button class="btn dark full next-quiz" ${!state.quiz[s.key]?'disabled':''}>${state.quizStep===2?'生成我的推荐':'下一步'}</button></div>`)}
function result(){return page(`<span class="eyebrow">YOUR YAO MATCH</span><h1 class="title">你的今日一杯</h1><div class="result-card"><span class="match">92% MATCH</span><div class="result-orb">山雾</div><h2>清爽的大瑶山</h2><p class="subtitle">柑橘 · 乌龙茶 · 轻草本 · 气泡<br>酒精度 4.2%</p><div class="reason">你选择了「${state.quiz.scene||'旅行尝鲜'}」和「${state.quiz.flavor||'清爽'}」。山雾入口轻盈，气泡与柑橘让草本香气更容易亲近，很适合今天。</div><br><button class="btn dark full add-drink" data-drink="fog">立即点单 · ¥28</button><br><br><button class="text-btn reset-quiz">换一杯</button></div>`)}
function ingredients(){const list=[['瑶皇酒','🍶'],['气泡水','🫧'],['乌龙茶','🍵'],['柠檬','🍋'],['橙汁','🍊'],['可乐','🥤'],['椰奶','🥥'],['咖啡','☕'],['冰块','🧊']];return page(`<span class="eyebrow">WHAT YOU HAVE</span><h1 class="title">手边有什么？</h1><p class="subtitle">选择至少 3 种材料，AI 会给你两个真正做得出来的配方。</p><div class="ingredient-grid">${list.map(([n,e])=>`<button class="ingredient ${state.ingredients.has(n)?'active':''}" data-ing="${n}"><b>${e}</b><small>${n}</small></button>`).join('')}</div><div class="bottom-action"><button class="btn dark full generate-recipes">用 ${state.ingredients.size} 种材料生成配方</button></div>`)}
function recipes(){return page(`<span class="eyebrow">AI GENERATED · 2 RECIPES</span><h1 class="title">今晚可以这样调</h1><p class="subtitle">根据你现有的 ${[...state.ingredients].join('、')} 生成。</p><article class="recipe"><span class="recipe-num">01</span><h3>山雾乌龙</h3><p>瑶皇酒 30ml + 乌龙茶 60ml + 气泡水 90ml<br>加满冰块，轻搅 6 秒。</p><div class="chips"><span class="chip active">清爽</span><span class="chip">茶感</span><span class="chip">4.2%</span></div><button class="btn dark save">收藏配方</button></article><article class="recipe"><span class="recipe-num">02</span><h3>月下柠风</h3><p>瑶皇酒 25ml + 柠檬汁 10ml + 气泡水 100ml<br>杯口挤柠檬皮，香气会更明亮。</p><div class="chips"><span class="chip active">酸香</span><span class="chip">轻草本</span><span class="chip">3.8%</span></div><button class="btn dark save">收藏配方</button></article>`)}
function pattern(){return page(`<span class="eyebrow">MY YAO PATTERN</span><h1 class="title">把这一杯<br>变成你的</h1><p class="subtitle">纹样灵感来自山、雾与植物的几何秩序；以当代方式重新生成，不复制传统纹样。</p><div class="pattern-stage"><div class="pattern" style="filter:hue-rotate(${state.pattern*55}deg)"></div></div>${section('选择灵感')}<div class="chips"><button class="chip active">山</button><button class="chip">雾</button><button class="chip">植物</button><button class="chip">水</button><button class="chip">夜</button></div><button class="btn dark full new-pattern">再生成一款</button><br><br><button class="btn ghost full save">保存我的数字酒签</button>`)}
function mine(){return page(`<div class="profile-card"><div class="profile-row"><span class="avatar">瑶</span><div><strong>山雾型饮者</strong><p>已在大瑶山留下 2 次微醺记忆</p></div></div><div class="dna"><i style="height:82%"><small>清爽</small></i><i style="height:60%"><small>茶感</small></i><i style="height:38%"><small>甜度</small></i><i style="height:45%"><small>酒感</small></i><i style="height:68%"><small>草本</small></i></div></div><div class="stats"><div class="stat"><b>2/3</b><small>酒谱解锁</small></div><div class="stat"><b>4</b><small>收藏配方</small></div><div class="stat"><b>2</b><small>我的瑶纹</small></div></div>${section('我的服务')}<div class="list"><button class="mode-card go-order"><span class="mode-icon">▣</span><span><strong>我的订单</strong><small>查看取餐码与历史订单</small></span><b>›</b></button><button class="mode-card go-pattern"><span class="mode-icon">◇</span><span><strong>我的瑶纹</strong><small>酒签、壁纸与个性瓶贴</small></span><b>›</b></button><button class="mode-card"><span class="mode-icon">▤</span><span><strong>旅行装复购</strong><small>离开金秀，也能复刻这一杯</small></span><b>›</b></button></div>`)}
function checkout(){return page(`<span class="eyebrow">CHECKOUT</span><h1 class="title">确认你的瑶山</h1><div class="menu-item"><div class="thumb">🫧</div><div><h3>山雾 · LIGHT</h3><p>少冰 · 标准甜 · 4.2%</p><strong>¥28</strong></div><div class="stepper"><button>−</button><b>${state.cart}</b><button>＋</button></div></div>${section('取饮方式')}<div class="chips"><button class="chip active">到店自取</button><button class="chip">堂食</button></div><div class="store active"><span class="store-icon">⌖</span><div><strong>金秀瑶都·山酿体验店</strong><small>预计 8 分钟后可取</small></div></div>${section('订单金额')}<div class="store"><div style="width:100%;display:flex;justify-content:space-between"><span>合计</span><strong>¥${28*state.cart}</strong></div></div><div class="bottom-action"><button class="btn dark full pay">模拟支付 · ¥${28*state.cart}</button></div>`)}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>navigate(b.dataset.tab,false));document.querySelectorAll('.go-quiz').forEach(b=>b.onclick=()=>{state.quizStep=0;navigate('quiz')});document.querySelectorAll('.go-mix').forEach(b=>b.onclick=()=>navigate('mix'));document.querySelectorAll('.go-order').forEach(b=>b.onclick=()=>navigate('order'));document.querySelectorAll('.go-pattern').forEach(b=>b.onclick=()=>navigate('pattern'));document.querySelectorAll('.go-ingredients').forEach(b=>b.onclick=()=>navigate('ingredients'));document.querySelectorAll('.go-checkout').forEach(b=>b.onclick=()=>navigate('checkout'));document.querySelectorAll('.add-drink').forEach(b=>b.onclick=()=>{state.cart++;toast('已加入酒篮');setTimeout(()=>navigate('order'),450)});document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{state.quiz[b.dataset.key]=b.dataset.choice;render()});document.querySelectorAll('.next-quiz').forEach(b=>b.onclick=()=>{state.quizStep++;render()});document.querySelectorAll('.reset-quiz').forEach(b=>b.onclick=()=>{state.quizStep=0;state.quiz={scene:'',flavor:'',strength:''};render()});document.querySelectorAll('[data-ing]').forEach(b=>b.onclick=()=>{const n=b.dataset.ing;state.ingredients.has(n)?state.ingredients.delete(n):state.ingredients.add(n);render()});document.querySelectorAll('.generate-recipes').forEach(b=>b.onclick=()=>navigate('recipes'));document.querySelectorAll('.new-pattern').forEach(b=>b.onclick=()=>{state.pattern++;render();toast('已生成新的专属纹样')});document.querySelectorAll('.save').forEach(b=>b.onclick=()=>toast('已保存到「我的瑶山」'));document.querySelectorAll('.pay').forEach(b=>b.onclick=()=>{state.cart=0;toast('支付成功，取餐码 YAO-0268');setTimeout(()=>navigate('mine',false),900)})}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1800)}
document.querySelector('#backBtn').onclick=()=>{const prev=state.history.pop();navigate(prev||'home',false)};
render();
